title: "DATA STORE"
author: "grace"
email: "tadntqna@gmaill.com"
description: "Đây là mô tả về website của tôi."
baseurl: "/store-sheet-data" # Đường dẫn gốc của site
url: "https://dien-github.github.io" # URL gốc của site
theme: jekyll-theme-minimal
collections:
  sheets:
    output: true
    permalink: /sheets/:path/